### PR TITLE
GitHub: Ignore Other Known Unimplemented Events

### LINKED ISSUE #2: Unknown Git Events
These events are currently unknown:

- deployment
- deployment_status
- fork
- member
- page_build
- pull_request_review
- pull_request_review_comment
- repository_vulnerability_alert
- star
- team
- team_add
- watch

### PR DESCRIPTION
**Pull request by dargmuesli**
Closes #2.

### CODE REVIEW

**Comment by flxai** [comment]
Deployed!

**Comment by dargmuesli** [comment]
For flipdot's IRC? Are you the one who knows on which Pi this is running? xD

**Comment by flxai** [comment]
Yeah, it's `power-pi.fd`!

**Comment by dargmuesli** [comment]
🔥

**Pull request merged**
